### PR TITLE
dark mode in violation page

### PR DESCRIPTION
**Pull request by sunny52525**
## Related Issue
#384 

Fixes #

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
There wasn't much change needed for this page.

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Hi, the code looks good so far - I'm about to test it.

Before I can merge it if it tests well, please take the change out of app/build.gradle - the realm_app_id should go in the realm.properties file, not the app/build.gradle file.

**Review by Sheeri — CHANGES_REQUESTED** [review]
The Violation page itself looks great! When I go to choose a violation, however, the menu items are white text on a white background. Everything else looks fine, including the "Issued to:" menu - it's only the violation menu/picking a violation that is a problem.

**Comment by sunny52525** [comment]
I'm not sure which part you meant @Sheeri

**Comment by Sheeri** [comment]
Hi @sunny52525 - I mean when you tap on the "Violation" field to add an item, a selection menu pops up with white text on a white background like this:
Screenshot_20201014-170853_O-FISH

**Comment by sunny52525** [comment]
I don't know if I am doing something wrong but for some reason nothing comes up in my device,I even tried with the main branch but still same
image

**Comment by Sheeri** [comment]
@sunny52525 Try now? It looks like you were an early adopter of the sandbox, before we put some starter data into the menu items. I changed that for you.

**Comment by sunny52525** [comment]
@Sheeri nope, still the same.

**Comment by sunny52525** [comment]
@Sheeri no worries, I created a new account. Its showing now. I will fix that page as soon as I get free

**Comment by sunny52525** [comment]
Screenshot_20201016-004633
Screenshot_20201016-004642

**Comment by sunny52525** [comment]
extra colors that I added are from main branch to resolve merge conflicts

**Comment by sunny52525** [comment]
This PR is messed up, reopening a clean one.

**Pull request closed without merging**
