### PR TITLE
changed 'New Boarding' to 'Draft Boarding'

### PR DESCRIPTION
**Pull request by seemagawaradi**
the issue addressed: #353

### CODE REVIEW

**Comment by Sheeri** [comment]
Hello @ seemagawaradi - thanks for this PR! Our team will review this pull request within three business days. While you are waiting, you can work on another issue if you'd like.

We really appreciate the effort - thanks!

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/QKVtiwN0/372-review-prs)

**Review by am-MongoDB — CHANGES_REQUESTED** [review]
The current PR changes the title to "Draft Boarding" in all cases. Instead we need:
- If a new boarding report is being created (not a previously saved draft) then the title should be "New Boarding"
- If a saved draft boarding (in the model, `draft == true`) then the title should be "Draft Boarding"

**Comment by seemagawaradi** [comment]
Right! I'm sorry, I'm kind of new to this. Thanks for your input. I will definitely look into it and change it.

**Comment by Sheeri** [comment]
Hi @seemagawaradi ! When you have a moment, can you please comment on issue #353? We cannot assign it to you until you have commented on it so other people may think it's available to work on.

Also our guidelines state that if an issue isn't commented on in three days (72 hours) it will be considered abandoned. It doesn't have to be fixed, just let us know you're still working on it.

Thanks!

**Comment by Sheeri** [comment]
(The guidelines weren't up when you started with on it,  so we wanted to give you a heads up. The guidelines in full are at: https://wildaid.github.io/contribute/ )

**Pull request closed without merging**
