### PR TITLE
Added Dark mode to basic information page

### LINKED ISSUE #368: Add Dark Mode button and change the 'Me' page accordingly
Users frequently find themselves in situations where they are using the app in very bright sunlight, or at night. Please add a Dark Mode button, and change the 'Me' page accordingly. 

This is the screen when the user clicks their avatar on the home screen. 

The screen should look like this - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me
Dark mode is off by default, and has the light background; when Dark mode is toggled on, the dark theme should be applied. 

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode  
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode   
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### LINKED ISSUE #378: Dark Mode for Basic Information page
This issue depends on #368 being completed. 

When Dark Mode is on - the Basic Information page should look like this: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591786_Boarding_-_Basic_Information

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not), and colors should be stored in:
app/src/main/res/values-night/colors.xml 
app/src/main/res/values/colors.xml 

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by sunny52525**
## Related Issue
#378 
Fixes #378 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [ ] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any relevant screenshots here** 
wp6704977-viper-valorant-wallpapers (1)

Screenshot in original resolution
[light](https://drive.google.com/file/d/1DYbRgOQqMuwBwjsQxXBpkEXpFPqyO38H/view?usp=drivesdk)
[dark](https://drive.google.com/file/d/1DaB_g97CmURLzA-H3LW1bAuDPlGvAwbp/view?usp=drivesdk)

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Hi @sunny52525 - I added some changes, so that colors.xml has the same structure in values/ and values/night, so make sure to do a git pull on your branch.

Also, the boarding details look good in dark mode, except that the background is still white. This is most easily seen at the bottom. Can you fix that? (EDITED to add - also, the latitude and longitude is still black text).

Here's a screenshot:

Screenshot_20201008-160245_O-FISH

**Comment by sunny52525** [comment]
@Sheeri Toolbar should black or main_blue in dark mode?

**Comment by sunny52525** [comment]
fixed the background
Screenshot_20201009-021241

**Review by Sheeri — APPROVED** [review]

**Review by Sheeri — APPROVED** [review]
Huzzah! Looks great!

Screenshot_20201008-171937_O-FISH

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

(Plenty of other dark mode tickets and now that all the different dark mode work has been merged in, it should be much easier. Feel free to comment on another issue and I will assign it to you!)

**Pull request merged**
