### PR TITLE
Adding color to edit and photo

### PR DESCRIPTION
**Pull request by yoobi**

### CODE REVIEW

**Comment by Sheeri** [comment]
Hi @yoobi - Thanks for your pull request! This is a critical fix for accessibility.

We will review this as a fix for #247 within 3 days.

**Comment by yoobi** [comment]
Sure, I've added the color into the colors files so it'll be easier for you to add it somewhere else later :)

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/QKVtiwN0/372-review-prs)

**Comment by am-MongoDB** [comment]
This PR currently changes some of the edit, attachment, and camera icons to 666666, but others still use the lighter grey – all of these icons in all of the views need to use the same color
image

**Review by am-MongoDB — CHANGES_REQUESTED** [review]
This PR currently changes some of the edit, attachment, and camera icons to 666666, but others still use the lighter grey – all of these icons in all of the views need to use the same color
image

**Comment by yoobi** [comment]
Oh you're right I didn't see the other icons, I've made the change

**Review by am-MongoDB — CHANGES_REQUESTED** [review]
There are still icons using the lighter grey color
image
image

**Comment by Sheeri** [comment]
@yoobi when you have a moment,  can you please comment on issue #247? We cannot assign it to you until you have commented on it so other people think it's available to work on. 

Also our guidelines state that if an issue isn't commented on in three days (72 hours) it will be considered abandoned. It doesn't have to be fixed,  just let us know you're still working on it.  

Thanks!

**Review by Sheeri — CHANGES_REQUESTED** [review]
@yoobi - There are 5 icons on 3 different pages of the app that still are too light. Please make sure to build this locally in your emulator to check all the pages and icons; there's a sandbox instance and you can make your own login to it to use the app - see the instructions at https://wildaid.github.io/contribute/sandbox.html

Pages and status:
(attachment, pencil edit, and camera/note icons)
Vessel page - pencil and attachment for vessel info, last delivery, and EMS look good
Crew page - captain, crew members 1 & 2 look good
**Activity page - Activity, Fishery, Gear - the attachment icon is still too light.**
Catch page - attachment and edit icons look good
Violation page - Violation attachment and edit icons look good, **Seizures attachment icon is too light.**
**Risk page - Attachment icon too light**
Note page - attachment and edit icons good.

**Review by Sheeri — APPROVED** [review]
I have verified that all the icons on the pages have the darker color. Great work @yoobi !!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by yoobi** [comment]
Hello, Hacktoberfest rules has changed could you add the label hacktoberfest-accepted on the PR ? thanks :)

**Comment by Sheeri** [comment]
The guidelines at https://hacktoberfest.digitalocean.com/details say:

"Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted."

This repo has the hacktoberfest topic, so once the pull request has been merged or approved, it will count towards your participation. The 'hacktoberfest-accepted' tag is not necessary, as this repo has the 'hacktoberfest' topic.

If you want to track your progress, you can login to your hacktoberfest profile page at https://hacktoberfest.digitalocean.com/profile

Here's what mine currently looks like:
Screen Shot 2020-10-07 at 12 44 36 PM

The clock on the left and the "Mature in" at the right show that once the 14-day waiting period is over, my PRs will count towards hacktoberfest participation. 

Here's the legend on the page:
Screen Shot 2020-10-07 at 12 46 10 PM

So if you have any doubts or worries about ANY pull request - in this repo or any other - you can check your status.

**Comment by yoobi** [comment]
Oh okay I though as it has to had the hacktoberfest-accepted label, after re-reading it you're right :) thanks

**Comment by Sheeri** [comment]
Hi @yoobi! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
