### PR TITLE
Issue #355 x on officer profile to close

### PR DESCRIPTION
**Pull request by jokopriyono**
I had already solved Issue #355 "X on officer profile to close" please review my code, I hope it helps

### CODE REVIEW

**Review by lebedynskyi — APPROVED** [review]
Approved

**Review by Sheeri — APPROVED** [review]
Functionality works, code approved by VL.

**Comment by Sheeri** [comment]
@jokopriyono Congratulations! You have submitted an excellent PR that we have merged in.

Thank you! You are making the O-FISH app better, and it will be that much easier for WildAid to keep the world's oceans clean. We hope you'll submit another contribution!

**Comment by Sheeri** [comment]
Hi @jokopriyono! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
