### PR TITLE
Save dark mode status in realm and update the me page

### LINKED ISSUE #368: Add Dark Mode button and change the 'Me' page accordingly
Users frequently find themselves in situations where they are using the app in very bright sunlight, or at night. Please add a Dark Mode button, and change the 'Me' page accordingly. 

This is the screen when the user clicks their avatar on the home screen. 

The screen should look like this - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me
Dark mode is off by default, and has the light background; when Dark mode is toggled on, the dark theme should be applied. 

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode  
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode   
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by thearavind**
## Related Issue

Fixes #368

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [x] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here** 

Dark
Light

### CODE REVIEW

**Review by Sheeri — COMMENTED** [review]
@am-MongoDB This adds an entry to a new collection called DarkMode, and currently is not working with Realm Sync as that collection does not exist. 

If it's something to be stored in the database, I think a darkMode field in the User collection makes the most sense.

But - does it have to be stored in Realm?

(and yes, I understand this is one of the difficulties of having an extra parameter on top of just using the system status.... :-\ )

**Comment by andrewjamesmorgan** [comment]
If we want the same value to apply across all devices (multiple Android phones/tablets and an iPhone) then we should ideally store the state in the ‘User’ doc, but that isn’t currently sync’d with the mobile apps. Probably better to just store it as local state in the device, whether outside of Realm or in a non-sync’d realm, as it’s reasonable that someone would want different values on say their phone and tablet.

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/0hZuNJp0/395-review-prs)

**Comment by am-MongoDB** [comment]
The logout modal is unusable in dark mode, as you can't see the buttons 
image

**Comment by thearavind** [comment]
Hi @am-MongoDB I have fixed the dialog colors in dark mode

DarkDialog

**Review by Sheeri — APPROVED** [review]
This looks good! The modal for when the user was at "At Sea" and clicked the toggle again, was still on a white theme, so I fixed that by tweaking the values-night/styles.xml - there were some more Light instances that needed to be changed to DayNight. Additionally, I updated the values-night/colors.xml with values to match the style guide at https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode - e.g.  main_blue was a big one.

**Comment by Sheeri** [comment]
@thearavind you did a TON of great work here.....
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by thearavind** [comment]
Thanks a lot, @Sheeri and @am-MongoDB 🙂. Sure would love to contribute more 👍

**Comment by Sheeri** [comment]
@thearavind - There are plenty of dark mode issues at https://github.com/WildAid/o-fish-android/issues - you would be great for those!

**Pull request merged**
