### PR TITLE
fix: change android input type to use numeric keyboard by default

### LINKED ISSUE #272: EMS registry number should be a number
Please show the numeric keyboard as default for entering information into the EMS section - registry number.

### PR DESCRIPTION
**Pull request by subbramanil**
## Related Issue

Fixes #272

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here** 

Screenshot_1601642116

### CODE REVIEW

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/QKVtiwN0/372-review-prs)

**Review by am-MongoDB — APPROVED** [review]

**Comment by am-MongoDB** [comment]
Thanks @subbramanil !

**Comment by Sheeri** [comment]
Hi @subbramanil! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Comment by subbramanil** [comment]
@Sheeri Appreciate it. Just replied in the MongoDB Community Forum with the link to the PR. :)

**Pull request merged**
