### PR TITLE
Issue/414

### LINKED ISSUE #414: Cleanup: don't use hardcoded text and colors
After dark mode is complete, look through all the code and make sure any text and colors are using shared resources, not hard-coded.

### PR DESCRIPTION
**Pull request by yoobi**
## Related Issue

Fixes #414

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [ ] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [x] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

### CODE REVIEW

**Comment by Sheeri** [comment]
Thank you so much for submitting your PR! Our team will review it and get back to you within 3 working days. Feel free to work on another issue as we verify this fix.

**Review by Sheeri — CHANGES_REQUESTED** [review]
Hi @yoobi - unfortunately, the changes in CrewFragment.kt are giving me errors. I don't actually see where "it" is defined in the file so the errors seem valid to me (e.g. not my build env or something). Can you make changes (or suggest what I need to change in my build env?)

o-fish-android/app/src/main/java/org/wildaid/ofish/ui/crew/CrewFragment.kt: (39, 23): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections

o-fish-android/app/src/main/java/org/wildaid/ofish/ui/crew/CrewFragment.kt: (40, 36): Unresolved reference: it

o-fish-android/app/src/main/java/org/wildaid/ofish/ui/crew/CrewFragment.kt: (41, 36): Unresolved reference: it

**Comment by yoobi** [comment]
oh you're right it was missing an import. I'm pushing right now

**Review by Sheeri — APPROVED** [review]
Thanks! It works now with the import. Will merge.

**Comment by yoobi** [comment]
The "Reason for risk" is in `item_report_risk.xml`

**Comment by Sheeri** [comment]
Can you show me a screenshot of where that shows up in the app for the user? I can't locate it.

**Comment by yoobi** [comment]
I only saw this in the code
Screenshot 2021-10-05 at 17 45 43
Screenshot 2021-10-05 at 17 46 18

**Pull request merged**
