### PR TITLE
Dark Mode for Risk Page

### LINKED ISSUE #385: Dark Mode for Risk page
This issue depends on #368 being completed. 

When Dark Mode is on - the Risk page should look like this: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591792_Boarding_-_Risk

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by ashwinpilgaonkar**
## Related Issue

Fixes #385

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here** 
image
image

### CODE REVIEW

**Review by Sheeri — APPROVED** [review]
Looks good, works as specified, and night mode colors are correct.

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Hi @ashwinpilgaonkar! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Comment by ashwinpilgaonkar** [comment]
> Hi @ashwinpilgaonkar!
> We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

Hi @Sheeri I wrote a post on the community forums, but it isn't allowing me to link all 3 of my PRs. It gives me an error stating that new users are allowed to post only 2 links, but in the end allows me to only link 1 PR.

**Comment by Sheeri** [comment]
Hi @ashwinpilgaonkar you only need to link 1 PR to get the badges :D

**Comment by ashwinpilgaonkar** [comment]
> Hi @ashwinpilgaonkar you only need to link 1 PR to get the badges :D

Oh, okay! :D

**Pull request merged**
