### PR TITLE
Add dark mode to boarding record page

### PR DESCRIPTION
**Pull request by cfsnsalazar**

### CODE REVIEW

**Comment by cfsnsalazar** [comment]
Most of the work that I did was around the toolbar and the few parts of the layout file

As this is my first ticket in this repo, I could be missing something. Please, let me know if that is the case

**Review by Sheeri — CHANGES_REQUESTED** [review]
Wow, @cfsnsalazar this is fantastic! There's only one text element that's not showing up with the right color, and that's the time (right under the date, it's in black so it's very hard to see, I circled it in red):
Screenshot_20201012-210904_O-FISH

The map itself is also not in dark mode. There was another map put into dark mode in this pull request, which might help figure out what needs to be changed here: https://github.com/WildAid/o-fish-android/pull/392/files

**Comment by cfsnsalazar** [comment]
> Wow, @cfsnsalazar this is fantastic! There's only one text element that's not showing up with the right color, and that's the time (right under the date, it's in black so it's very hard to see, I circled it in red):
> Screenshot_20201012-210904_O-FISH
> 
> The map itself is also not in dark mode. There was another map put into dark mode in this pull request, which might help figure out what needs to be changed here: https://github.com/WildAid/o-fish-android/pull/392/files

Good eye!. Just updated that TextView to use the correct color listed in values-night/colors.xml and values/colors.xml

boarding_light_mode
boarding_dark_mode

**Comment by Sheeri** [comment]
Hi @cfsnsalazar - that changed the time color, thanks! The map is still in light mode though. The pull request at https://github.com/WildAid/o-fish-android/pull/392/files changed the map to dark mode on the "basic information" page when boarding a vessel, so I would expect that something similar needs to be done for the boarding record itself.

Here's what the "Basic Information" page looks like in dark mode - the map is all dark colors:
Screenshot_20201013-094724_O-FISH

**Comment by cfsnsalazar** [comment]
@Sheeri  any other comments?

**Review by Sheeri — APPROVED** [review]
Perfect aa

**Review by Sheeri — APPROVED** [review]
Perfect!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Fixes #376

**Comment by Sheeri** [comment]
Hi @cfsnsalazar! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
