### PR TITLE
Notes page dark mode

### LINKED ISSUE #386: Dark Mode for Notes page
This issue depends on #368 being completed. 

When Dark Mode is on - the Notes page should look like this:  https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591793_Boarding_-_Notes

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by sunny52525**
## Related Issue

Fixes #386 

## Checklist:

- [x ] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
I added new colors.xml which is used when system theme is changed to dark. Which means not only notes page is changed but other pages too. It will be easier to theme other section.

* **Optional: Add any relevant screenshots here** 
Screenshot_20201006-044305

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
This looks FANTASTIC @sunny52525! I even love how you set the cursor to white, great job!

I have one nitpick - it doesn't look like the camera and pencil icons are #979797. Are they set to that? (It's always hard to tell on displays).

**Comment by sunny52525** [comment]
must have missed,added that color now

**Review by Sheeri — APPROVED** [review]
Perfect!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

(there's lots more dark mode issues up for grabs, and now that we have your library of colors in the codebase, they should be easy!

**Comment by sunny52525** [comment]
Yeah sure. I will start with _Basic Information_ page

**Comment by Sheeri** [comment]
Hi @sunny52525! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
