### PR TITLE
Feature/dark mode vessel information page

### LINKED ISSUE #379: Dark Mode for Vessel Information page
This issue depends on #368 being completed. 

When Dark Mode is on - the Vessel Information page should look like this:  https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591787_Boarding_-_Vessel   (Note that there is a separate issue for pull-down menus.)

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not), and colors should be stored in:
app/src/main/res/values-night/colors.xml 
app/src/main/res/values/colors.xml 

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by cfsnsalazar**
## Related Issue
Fixes #379 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Dark Mode

VesselInformationDarkEdit
LastDeliveryDarkEdit
EMSDarkEdit
VesselInformationDark

### CODE REVIEW

**Comment by cfsnsalazar** [comment]
The designs show a different workflow in regards to the EMS. Should that workflow be updated on this ticket? Is there a separate ticket for that?

**Comment by Sheeri** [comment]
Hi @cfsnsalazar these are known variants against the design with no plan to change:

- "add eletronic monitoring system" is a button in the design, and just + Add Electronic Monitoring System in the app
- "No electronic monitoring system" checkbox is out-of-date in the design (it was a design idea we had for a while, but didn't update when we did away with that functionality)
- "Remove Electronic Monitoring System" in the design vs. "Remove EMS" in the app

Was there anything else I missed?

**Review by Sheeri — CHANGES_REQUESTED** [review]
In app/src/main/res/values-night/colors.xml, black_2 is used in these places:

```
<color name="colorPrimary">@color/black_2</color>
<color name="colorAppBar">@color/black_2</color>
<color name="boarding_record_toolbar">@color/black_2</color>
<color name="boarding_record_status_bar">@color/black_2</color>
 <color name="vessel_info_toolbar">@color/black_2</color>
<color name="vessel_info_status_bar">@color/black_2</color>
<item name="colorPrimaryDark">@color/black_2</item>
```

I can see that you're duplicating what was done with the boarding record - but I don't think we should keep making variables for different toolbars and status bars. Can you consolidate those records into:
```
<color name="toolbar">@color/black_2</color>
<color name="statusBar">@color/black_2</color>
```

boarding_record_toolbar and boarding_record_status_bar are used in:
app/src/main/res/layout/fragment_report_details.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/java/org/wildaid/ofish/ui/reportdetail/ReportDetailFragment.kt

If that's getting too much for this PR, we can approve what is here and open a different issue to consolidate the variables.

Also, there's a bit more work to be done on the main part - when I select a Business for Last Delivery, the menu is black text on a black background. Here's a screenshot of 2 items in the Business menu, where I am selecting one of them - only when I select the item, does the text show up, because it's highlighted:

Screenshot_20201019-225641_O-FISH

**Comment by cfsnsalazar** [comment]
> In app/src/main/res/values-night/colors.xml, black_2 is used in these places:
> 
> 
> 
> ```
> 
> <color name="colorPrimary">@color/black_2</color>
> 
> <color name="colorAppBar">@color/black_2</color>
> 
> <color name="boarding_record_toolbar">@color/black_2</color>
> 
> <color name="boarding_record_status_bar">@color/black_2</color>
> 
>  <color name="vessel_info_toolbar">@color/black_2</color>
> 
> <color name="vessel_info_status_bar">@color/black_2</color>
> 
> <item name="colorPrimaryDark">@color/black_2</item>
> 
> ```
> 
> 
> 
> I can see that you're duplicating what was done with the boarding record - but I don't think we should keep making variables for different toolbars and status bars. Can you consolidate those records into:
> 
> ```
> 
> <color name="toolbar">@color/black_2</color>
> 
> <color name="statusBar">@color/black_2</color>
> 
> ```
> 
> 
> 
> boarding_record_toolbar and boarding_record_status_bar are used in:
> 
> app/src/main/res/layout/fragment_report_details.xml
> 
> app/src/main/res/values-night/colors.xml
> 
> app/src/main/res/values/colors.xml
> 
> app/src/main/java/org/wildaid/ofish/ui/reportdetail/ReportDetailFragment.kt
> 
> 
> 
> If that's getting too much for this PR, we can approve what is here and open a different issue to consolidate the variables.
> 
> 
> 
> Also, there's a bit more work to be done on the main part - when I select a Business for Last Delivery, the menu is black text on a black background. Here's a screenshot of 2 items in the Business menu, where I am selecting one of them - only when I select the item, does the text show up, because it's highlighted:
> 
> 
> 
> Screenshot_20201019-225641_O-FISH
> 
> 

@Sheeri No worries, I will cover the toolbar portion on this PR . 
Thanks for reviewing my PR . I will make the updates ASAP

**Comment by cfsnsalazar** [comment]
@Sheeri I have consolidated the variables and completed the work on the Business page. I decided not to touch the date picker since that is using the app theme

Is there anything else you want me to update?

By the way, thanks for the explanation related to the EMS

**Comment by Sheeri** [comment]
Hrm - The menu to select "Business" under "Last Delivery" still has black text on a black background.

However, I noticed that in the latest build on the main branch, the Vessel page is all set in dark mode (including the Business menu). This is because other dark mode issues have been solved, and many components are reused in the code.

I'm going to close this pull request - I won't mark it invalid, since you did a ton of work here and should get hacktoberfest credit. But it seems the work has already been completed elsewhere.

**Comment by cfsnsalazar** [comment]
@Sheeri  No problem, I understand. It looks like I did not receive hacktoberfest credit for this PR though =(  .

**Comment by Sheeri** [comment]
@cfsnsalazar weird, it's not showing up at hacktoberfest.digitalocean.com/profile ?

**Comment by Sheeri** [comment]
Oh! I see. I've added the hacktoberfest-accepted label, hopefully it will show up now?

**Comment by cfsnsalazar** [comment]
@Sheeri Thanks. It does show up now!

**Pull request closed without merging**
